### ISSUE TITLE
Crash: Error converting value "Lead" to type 'UWPCommLib.Api.UWPComm.Models.Collaborator+RoleType'. Path 'projects[1].collaborators[10].role', line 1, position 3444.

### ISSUE THREAD

**Issue by chingucoding** [UWPCommunity/UWPCommunityApp#117]
After invoking the "launch" item in the navigation, I get the following crash:

![Image showing crash of app](https://user-images.githubusercontent.com/16122379/99069945-9db01800-25af-11eb-870a-8d9d517644a3.png)

**Comment by yoshiask** [comment]
Fixed in release 1.2.3. It'll take longer than I expected to get this published, because VS 16.8 is not playing nicely with my web requests.

**Comment by yoshiask** [comment]
Release 1.2.3 is now in certification
